import java.util.Properties
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    `kotlin-dsl`
    `java-test-fixtures`
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

kotlin {
    compilerOptions { jvmTarget = JvmTarget.JVM_17 }
}

dependencies {
    testImplementation(platform(libs.junit.bom))
    testImplementation(libs.junit.jupiter)
    testImplementation(kotlin("test"))
    testRuntimeOnly(libs.junit.platform.launcher)

    testFixturesApi(gradleTestKit())
}

val lvmVersion: Provider<String> = providers
    .fileContents(layout.projectDirectory.file("../../gradle.properties"))
    .asText
    .map { text -> Properties().apply { load(text.reader()) }.getProperty("VERSION_NAME") }

abstract class GenerateLvmBuildInfo : DefaultTask() {
    @get:Input
    abstract val constants: MapProperty<String, String>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val file = outputDirectory.file("tech/annexflow/lvm/blueprint/common/LvmBuildInfo.kt").get().asFile
        file.parentFile.mkdirs()
        file.writeText(
            buildString {
                appendLine("// Generated by :common:generateLvmBuildInfo. Do not edit.")
                appendLine("package tech.annexflow.lvm.blueprint.common")
                appendLine()
                appendLine("public object LvmBuildInfo {")
                constants.get().toSortedMap().forEach { (name, value) ->
                    appendLine("    public const val $name: String = \"$value\"")
                }
                appendLine("}")
            },
        )
    }
}

val generateLvmBuildInfo = tasks.register<GenerateLvmBuildInfo>("generateLvmBuildInfo") {
    description = "Generates LvmBuildInfo with the LVM version and the tested Kotlin, AGP and Gradle versions."
    constants.put("VERSION", lvmVersion)
    constants.put("TESTED_KOTLIN", libs.versions.kotlin)
    constants.put("TESTED_AGP", libs.versions.agp)
    constants.put("TESTED_GRADLE", gradle.gradleVersion)
    constants.put(
        "DETEKT_COMPOSE_RULES",
        libs.detekt.composeRules.map { "${it.module}:${it.versionConstraint.requiredVersion}" },
    )
    outputDirectory = layout.buildDirectory.dir("generated/lvmBuildInfo")
}

kotlin.sourceSets.named("main") { kotlin.srcDir(generateLvmBuildInfo) }

tasks.test {
    useJUnitPlatform()
    systemProperty("lvm.test.version", lvmVersion.get())
    systemProperty("lvm.test.kotlinVersion", libs.versions.kotlin.get())
    systemProperty("lvm.test.agpVersion", libs.versions.agp.get())
    systemProperty("lvm.test.gradleVersion", gradle.gradleVersion)
}
